/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package invetory;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.GraphicsEnvironment;
import java.awt.Point;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
//import net.proteanit.sql.DbUtils;
/**
 *
 * @author 
 */

public class FormBarangKeluar extends javax.swing.JDialog {
private Connection con; 
private Statement stat; 
private ResultSet res;
    /**
     * Creates new form Inventory_main
     * @param parent
     * @param modal
     */
    
    public FormBarangKeluar(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        getContentPane().setBackground(new Color(245, 245, 245));
        
        Dimension windowSize = getSize();
        GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
        Point centerPoint = ge.getCenterPoint();
        int dx = centerPoint.x - windowSize.width / 2;
        int dy = centerPoint.y - windowSize.height / 2;    
        setLocation(dx, dy);
        koneksikeluar();
        tabel2();
        btnsavekeluar.setText("Simpan");
    }
    
    private void koneksikeluar() { 
        try { 
          Class.forName("com.mysql.jdbc.Driver"); 
          con = DriverManager.getConnection("jdbc:mysql://localhost/inventory_barang", "root", ""); 
          stat = con.createStatement(); 
      } catch (Exception e) { 
          JOptionPane.showMessageDialog(null, e); 
          } 
}
    
    private void kosongkan(){
        txtkodekeluar.setText("");
        txtnamakeluar.setText("");
        txtjumlahkeluar.setText("");
        txtkondisikeluar.setSelectedIndex(-1); 
//        txtid_kategori.setText("");
//        txttemp_kode.setText("");
        txttanggalmasuk.setText("");
        txtkodekeluar.requestFocus();
    }
    
    private void kondisiKeluar(){ 
    txtkondisikeluar.addItem("Baik"); 
    txtkondisikeluar.addItem("Rusak Ringan");
    txtkondisikeluar.addItem("Rusak Berat"); 
    txtkondisikeluar.setSelectedIndex(-1); 
}
    
//    private void BtnEnabled(boolean x){
//        btnedit.setEnabled(x);
//        btndelete.setEnabled(x);
//    }

    
    private void tabel2(){ 
        String count_rows = String.valueOf(tbl2.getRowCount());
        lblcount_rows.setText("Jumlah Data : " + count_rows);
        DefaultTableModel t = new DefaultTableModel();
        t.addColumn("Kode Barang"); 
        t.addColumn("Nama Barang");
        t.addColumn("Tanggal Masuk"); 
        t.addColumn("Jumlah"); 
        t.addColumn("Kondisi"); 
        tbl2.setModel(t); 
            try { 
                res = stat.executeQuery("select * from inventory_barang_masuk"); 
                   while (res.next()) { 
                      t.addRow(new Object[]{
                      res.getString("Kd_Barang"),
                      res.getString("Nama_Barang"), 
                      res.getString("Tanggal_Masuk"),  
                      res.getString("Jumlah"), 
                      res.getString("Kondisi") 
                   }); 
                   }
            } catch (Exception e) { 
               JOptionPane.showMessageDialog(rootPane, e); 
              }
    }
    

    private void GetDataView(){
        int i = tbl2.getSelectedRow();
        if(i==-1){return;}
            String code = (String)tbl2.getValueAt(i,0);
            String code1 = (String)tbl2.getValueAt(i,1);
            String code2 = (String)tbl2.getValueAt(i,2);
            String code3 = (String)tbl2.getValueAt(i,3);
            String code4 = (String)tbl2.getValueAt(i,4);
            txtkodekeluar.setText(code);
            txtnamakeluar.setText(code1);
            txttanggalmasuk.setText(code2);
            txtjumlahkeluar.setText(code3);
            txtkondisikeluar.setSelectedItem(code4);   
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnsavekeluar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtkodekeluar = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtnamakeluar = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btncancelkeluar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtjumlahkeluar = new javax.swing.JTextField();
        txttanggalmasuk = new javax.swing.JTextField();
        txtkondisikeluar = new javax.swing.JComboBox<>();
        txttanggalkeluar = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl2 = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex) {
                return false;
            }
        };
        jLabel5 = new javax.swing.JLabel();
        lbl_action = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        btndeletekeluar = new javax.swing.JButton();
        lblcount_rows = new javax.swing.JLabel();
        jButton1keluar = new javax.swing.JButton();
        delete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Inventori Barang :: Data Barang");

        panel.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        panel.setForeground(new java.awt.Color(245, 245, 245));
        panel.setEnabled(false);

        jLabel1.setLabelFor(txtkodekeluar);
        jLabel1.setText("Kode");

        btnsavekeluar.setText("Simpan");
        btnsavekeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsavekeluarActionPerformed(evt);
            }
        });

        jLabel2.setLabelFor(txtnamakeluar);
        jLabel2.setText("Nama");

        txtkodekeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtkodekeluarActionPerformed(evt);
            }
        });

        jLabel4.setLabelFor(txtjumlahkeluar);
        jLabel4.setText("Tanggal masuk");

        txtnamakeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnamakeluarActionPerformed(evt);
            }
        });
        txtnamakeluar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnamakeluarKeyTyped(evt);
            }
        });

        jLabel6.setText("Kondisi");
        jLabel6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jLabel6KeyTyped(evt);
            }
        });

        btncancelkeluar.setText("Batal");
        btncancelkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelkeluarActionPerformed(evt);
            }
        });

        jLabel3.setText("Jumlah");

        txtjumlahkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtjumlahkeluarActionPerformed(evt);
            }
        });

        txtkondisikeluar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Baik", "Rusak Ringan", "Rusak Berat" }));
        txtkondisikeluar.setSelectedIndex(-1);

        jLabel7.setLabelFor(txtjumlahkeluar);
        jLabel7.setText("Tanggal keluar");

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(30, 30, 30)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtnamakeluar, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelLayout.createSequentialGroup()
                                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtkodekeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txttanggalmasuk, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(14, 14, 14))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelLayout.createSequentialGroup()
                                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(73, 73, 73)
                                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtjumlahkeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtkondisikeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(panelLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btncancelkeluar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnsavekeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(panelLayout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(txttanggalkeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12))))
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtkodekeluar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtnamakeluar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txttanggalmasuk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txttanggalkeluar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtjumlahkeluar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtkondisikeluar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnsavekeluar)
                    .addComponent(btncancelkeluar))
                .addGap(472, 472, 472))
        );

        tbl2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Kode", "Nama", "Tanggal Masuk", "Jumlah", "Kondisi"
            }
        ));
        tbl2.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tbl2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl2MouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tbl2MouseReleased(evt);
            }
        });
        tbl2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tbl2KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tbl2KeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tbl2);

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N

        lbl_action.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        lbl_action.setText("Data Barang");

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel8.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Keluarkan Barang");

        btndeletekeluar.setBackground(new java.awt.Color(255, 0, 0));
        btndeletekeluar.setText("keluar");
        btndeletekeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeletekeluarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btndeletekeluar)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(btndeletekeluar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblcount_rows.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        lblcount_rows.setText("Jumlah Data ");

        jButton1keluar.setBackground(new java.awt.Color(51, 51, 51));
        jButton1keluar.setFont(new java.awt.Font("Lucida Grande", 0, 11)); // NOI18N
        jButton1keluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventory_barang_image/Refresh.png"))); // NOI18N
        jButton1keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1keluarActionPerformed(evt);
            }
        });

        delete.setBackground(new java.awt.Color(51, 51, 0));
        delete.setText("Hapus");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblcount_rows, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(delete)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_action)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1keluar))
                    .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblcount_rows)
                            .addComponent(delete)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbl_action)
                            .addComponent(jButton1keluar, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(255, 255, 255)
                                .addComponent(jLabel5))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsavekeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsavekeluarActionPerformed
        try {
        stat.executeUpdate("insert into inventory_barang_keluar values (" 
        + "'" +  txtkodekeluar.getText()+"'," 
        + "'" + txtnamakeluar.getText()+"',"
        + "'" + txttanggalmasuk.getText()+"',"
        + "'" + txttanggalkeluar.getText()+"'," 
        + "'" + txtjumlahkeluar.getText()+ "',"
        + "'" + txtkondisikeluar.getSelectedItem()+ "')");
        this.tbl1();
        this.tbl2(); 
        kosongkan(); 
        JOptionPane.showMessageDialog(null, "Data Berhasil Dikeluarkan"); 
        } catch (Exception e) { 
        JOptionPane.showMessageDialog(null, "Perintah Salah : "+e);
        } 
    }//GEN-LAST:event_btnsavekeluarActionPerformed

    public void tbl1() {
    int a = 100;
    Object [][] data = new Object[a][8];
    try {
        int i = 0;
        while (res.next()){
        data [1][0]=res.getString("Kd_Barang");
        data [1][1]=res.getString("Nama_Barang");
        data [1][2]=res.getString("Tanggal_Masuk");
        data [1][3]=res.getString("Jumlah");
        data [1][4]=res.getString("Kondisi");
        i++;
        }
        String [] setJudul={"Kd_Barang","Nama_Barang","Tanggal_MAsuk","Jumlah","Kondisi"};
        tbl2.setModel(new DefaultTableModel(data, setJudul));
        data = new Object[1][8];
    } catch (Exception e){
      System.out.println("Gagal Tampil"+e.toString());
}
}

public void tbl2() {
    int a = 100;
    Object [][] data = new Object[a][8];
    try {
        int i = 0;
        while (res.next())
        {
        data [1][0]=res.getString("Kd_Barang");
        data [1][1]=res.getString("Nama_Barang");
        data [1][2]=res.getString("Tanggal_Masuk");
        data [1][3]=res.getString("Tanggal_Keluar");
        data [1][4]=res.getString("Jumlah");
        data [1][5]=res.getString("Kondisi");
        i++;
        }
        String [] setJudul={"Kd_Barang","Nama_Barang","Tanggal_Masuk","Tanggal_Keluar","Jumlah","Kondisi"};
        tbl2.setModel(new DefaultTableModel(data, setJudul));
        data = new Object[1][8];
        } catch (Exception e){
      System.out.println("Gagal Tampil"+e.toString());
}
}
    
    private void txtkodekeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtkodekeluarActionPerformed
         try {
            res=stat.executeQuery("select * from inventory_barang_masuk where "+ "Kd_Barang='" +txtkodekeluar.getText()
                +"'" ); 
            while (res.next()) {
                txtnamakeluar.setText(res.getString("Nama_Barang"));
                txttanggalmasuk.setText(res.getString("Tanggal_Masuk"));
                txtjumlahkeluar.setText(res.getString("Jumlah"));
                txtkondisikeluar.setSelectedItem(res.getString("Kondisi"));
            }
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }//GEN-LAST:event_txtkodekeluarActionPerformed

    private void txtnamakeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnamakeluarActionPerformed
    }//GEN-LAST:event_txtnamakeluarActionPerformed

    private void btncancelkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelkeluarActionPerformed
        btndeletekeluar.doClick();
    }//GEN-LAST:event_btncancelkeluarActionPerformed

    private void tbl2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl2MouseClicked
        GetDataView();
        txtkodekeluar.setEnabled(false);
        txtnamakeluar.setEnabled(false);
        txttanggalmasuk.setEnabled(false);
    }//GEN-LAST:event_tbl2MouseClicked

    private void btndeletekeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeletekeluarActionPerformed
          txtkodekeluar.requestFocus();
    }//GEN-LAST:event_btndeletekeluarActionPerformed

    private void tbl2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbl2KeyPressed
    }//GEN-LAST:event_tbl2KeyPressed

    private void tbl2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbl2KeyReleased
        GetDataView();
        txtkodekeluar.setEnabled(false);
        txtnamakeluar.setEnabled(false);
        txttanggalmasuk.setEnabled(false);
    }//GEN-LAST:event_tbl2KeyReleased

    private void tbl2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl2MouseReleased
        GetDataView();
        txtkodekeluar.setEnabled(false);
        txtnamakeluar.setEnabled(false);
        txttanggalmasuk.setEnabled(false);
    }//GEN-LAST:event_tbl2MouseReleased

    private void jButton1keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1keluarActionPerformed
        tabel2();
    }//GEN-LAST:event_jButton1keluarActionPerformed

    private void txtnamakeluarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnamakeluarKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnamakeluarKeyTyped

    private void jLabel6KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel6KeyTyped
    }//GEN-LAST:event_jLabel6KeyTyped

    private void txtjumlahkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtjumlahkeluarActionPerformed
    }//GEN-LAST:event_txtjumlahkeluarActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
        
          int ok=JOptionPane.showConfirmDialog(null,"Apakah Anda Yakin Untuk Menghapus Data Ini???","Confirmation",JOptionPane.YES_NO_OPTION);
            try { 
            stat.executeUpdate("delete from inventory_barang_keluar where " 
            + "Kd_Barang='"+txtkodekeluar.getText()
            +"'" );

            kosongkan();
            JOptionPane.showMessageDialog(null, "Data Berhasil Di Hapus"); 
            } catch (Exception e) { 
            JOptionPane.showMessageDialog(null, "Perintah Salah : "+e);
            }        // TODO add your handling code here:
    }//GEN-LAST:event_deleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormBarangMasuk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormBarangMasuk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormBarangMasuk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormBarangMasuk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(() -> {
            FormBarangKeluar dialog = new FormBarangKeluar(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncancelkeluar;
    private javax.swing.JButton btndeletekeluar;
    private javax.swing.JButton btnsavekeluar;
    private javax.swing.JButton delete;
    private javax.swing.JButton jButton1keluar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_action;
    private javax.swing.JLabel lblcount_rows;
    private javax.swing.JPanel panel;
    private javax.swing.JTable tbl2;
    private javax.swing.JTextField txtjumlahkeluar;
    private javax.swing.JTextField txtkodekeluar;
    private javax.swing.JComboBox<String> txtkondisikeluar;
    private javax.swing.JTextField txtnamakeluar;
    private javax.swing.JTextField txttanggalkeluar;
    private javax.swing.JTextField txttanggalmasuk;
    // End of variables declaration//GEN-END:variables
}
